spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/spring_subway
    username: user
    password: password
    driver-class-name: org.mariadb.jdbc.Driver
  sql:
    init:
      schema-locations: classpath*:schema.sql
      mode: always
